version: '3.8'

services:
        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
                environment:
                        - discovery.seed_hosts=elasticsearch
                        - cluster.initial_master_nodes=elasticsearch
                        - node.name=elasticsearch
                        - bootstrap.memory_lock=false
                        - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
