version: '3.8'

services:
 heartbeat:
  image: docker.elastic.co/beats/heartbeat:7.6.2
  dns:
   - 172.23.93.10
   - 172.24.80.10
  dns_search: xactware.com
  configs:
   - source: heartbeat_config
     target: /usr/share/heartbeat/heartbeat.yml
 logstash:
  image: docker.elastic.co/logstash/logstash:7.6.2
  secrets:
   - source: jira_logstash
     target: /usr/share/logstash/config/logstash.keystore
  configs:
   - source: logstash_config
     target: /usr/share/logstash/config/logstash.yml
   - source: pipeline_config
     target: /usr/share/logstash/config/pipeline.yml
   - source: jira_fields_def
     target: /usr/share/logstash/pipeline/jira_fields.config
   - source: jira_def
     target: /usr/share/logstash/pipeline/jira.config
 kibana:
  image: docker.elastic.co/kibana/kibana:7.6.2
  configs:
    - source: kibana_config
      target: /usr/share/kibana/config/kibana.yml
  ports:
   - 5601:5601
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  environment:
   - discovery.seed_hosts=elasticsearch
   - cluster.initial_master_nodes=elasticsearch
   - node.name=elasticsearch
   - bootstrap.memory_lock=false #Should be true, but whatever
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #Memory to use for elasticsearch process
  deploy:
   replicas: 1
   endpoint_mode: dnsrr
  ulimits:
   memlock:
    soft: -1
    hard: -1
secrets:
 jira_logstash:
  file: /home/jqt3of5/AutomationDashboard/logstash/config/logstash.keystore
configs:
 heartbeat_config:
  file: /home/jqt3of5/AutomationDashboard/heartbeat.yml
 logstash_config:
  file: /home/jqt3of5/AutomationDashboard/logstash/config/logstash.yml
 pipeline_config:	
  file: /home/jqt3of5/AutomationDashboard/logstash/config/pipelines.yml
 jira_def:
  file: /home/jqt3of5/AutomationDashboard/logstash/pipeline/jira.config
 jira_fields_def:
  file: /home/jqt3of5/AutomationDashboard/logstash/pipeline/jira_fields.config
 kibana_config:
  file: /home/jqt3of5/AutomationDashboard/kibana.yml

