version: '3.8'

services:
 heartbeat:
  image: docker.elastic.co/beats/heartbeat:7.6.2
  dns:
   - 172.23.93.10
   - 172.24.80.10
  dns_search: xactware.com
  configs:
   - source: heartbeat_config
     target: /usr/share/heartbeat/heartbeat.yml
  deploy:
   replicas: 0

 logstash:
  image: logstash_jire_poller:latest
  secrets:
   - source: jira_logstash
     target: /usr/share/logstash/config/logstash.keystore
  configs:
   - source: logstash_config
     target: /usr/share/logstash/config/logstash.yml
   - source: pipeline_config
     target: /usr/share/logstash/config/pipelines.yml
  volumes:
   - type: bind
     source: /Users/i52884/ELK/AutomationDashboard/logstash/pipeline
     target: /usr/share/logstash/pipeline
  deploy:
   replicas: 0

 kibana:
  image: docker.elastic.co/kibana/kibana:7.6.2
  configs:
    - source: kibana_config
      target: /usr/share/kibana/config/kibana.yml
  ports:
   - 5601:5601
  deploy:
    replicas: 1

 elasticsearch01:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  environment:
   - discovery.seed_hosts=elasticsearch03, elasticsearch02
   - cluster.initial_master_nodes=elasticsearch03, elasticsearch01, elasticsearch02
   - node.name=elasticsearch01
   - node.data=false
   - bootstrap.memory_lock=false #Should be true, but whatever
   - "ES_JAVA_OPTS=-Xms256m -Xmx256m" #Memory to use for elasticsearch process
 elasticsearch02:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  environment:
     - discovery.seed_hosts=elasticsearch03, elasticsearch01
     - cluster.initial_master_nodes=elasticsearch03, elasticsearch01, elasticsearch02
     - node.name=elasticsearch02
     - node.data=false
     - bootstrap.memory_lock=false #Should be true, but whatever
     - "ES_JAVA_OPTS=-Xms256m -Xmx256m" #Memory to use for elasticsearch process
 elasticsearch03:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  environment:
   - discovery.seed_hosts=elasticsearch02, elasticsearch01
   - cluster.initial_master_nodes=elasticsearch03, elasticsearch01, elasticsearch02
   - node.name=elasticsearch03
   - node.data=false
   - bootstrap.memory_lock=false #Should be true, but whatever
   - "ES_JAVA_OPTS=-Xms256m -Xmx256m" #Memory to use for elasticsearch process
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
  environment:
   - discovery.seed_hosts=elasticsearch01,elasticsearch02,elasticsearch03
   - bootstrap.memory_lock=false #Should be true, but whatever
   - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #Memory to use for elasticsearch process
  deploy:
   replicas: 1
   endpoint_mode: dnsrr

secrets:
 jira_logstash:
  file: /Users/i52884/ELK/AutomationDashboard/logstash/config/logstash.keystore

configs:
 heartbeat_config:
  file: /Users/i52884/ELK/AutomationDashboard/heartbeat.yml
 logstash_config:
  file: /Users/i52884/ELK/AutomationDashboard/logstash/config/logstash.yml
 pipeline_config:	
  file: /Users/i52884/ELK/AutomationDashboard/logstash/config/pipelines.yml
 kibana_config:
  file: /Users/i52884/ELK/AutomationDashboard/kibana.yml

