version: '3.8'

services:
        heartbeat:
                image: docker.elastic.co/beats/heartbeat:7.6.2
                dns:
                 - 172.23.93.10
                 - 172.24.80.10
                dns_search: xactware.com
                volumes:
                 - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
        logstash:
                image: docker.elastic.co/logstash/logstash:7.6.2
                volumes:
                 - ./logstash/config:/usr/share/logstash/config:ro
        kibana:
                image: docker.elastic.co/kibana/kibana:7.6.2
                volumes:
                 - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
                ports:
                 - 5601:5601
        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
                environment:
                        - discovery.seed_hosts=elasticsearch, elasticsearch_master
                        - cluster.initial_master_nodes=elasticsearch, elasticsearch_master
                        - node.name=elasticsearch
                        - bootstrap.memory_lock=false #Should be true, but whatever
                        - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m" #Memory to use for elasticsearch process
                deploy:
                        replicas: 2
                        endpoint_mode: dnsrr
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
        elasticsearch_master:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
                environment:
                        - discovery.seed_hosts=elasticsearch, elasticsearch_master
                        - cluster.initial_master_nodes=elasticsearch, elasticsearch_master
                        - node.name=elasticsearch_master
                        - bootstrap.memory_lock=false #Should be true, but whatever
                        - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m" #Memory to use for elasticsearch process
                deploy:
                        replicas: 1
                        endpoint_mode: dnsrr
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
